services:
  aemotor-loadbalancer:
    image: nginx:1.23.1-alpine
    container_name: aemotor-loadbalancer
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  node1:
    image: nginx:1.23.1-alpine
    container_name: node1
    volumes:
      - /home/marcella/Área de Trabalho/aemotor-loadbalancer/build/aemotor-reactjs/build:/usr/share/nginx/html
    ports:
      - "80"

  node2:
    image: nginx:1.23.1-alpine
    container_name: node2
    volumes:
      - /home/marcella/Área de Trabalho/aemotor-loadbalancer/build/aemotor-reactjs/build:/usr/share/nginx/html
    ports:
      - "80"

  node3:
    image: nginx:1.23.1-alpine
    container_name: node3
    volumes:
      - /home/marcella/Área de Trabalho/aemotor-loadbalancer/build/aemotor-reactjs/build:/usr/share/nginx/html
    ports:
      - "80"

  node4:
    image: nginx:1.23.1-alpine
    container_name: node4
    volumes:
      - /home/marcella/Área de Trabalho/aemotor-loadbalancer/build/aemotor-reactjs/build:/usr/share/nginx/html
    ports:
      - "80"